### ISSUE TITLE
남은 할 일 각 과목 리스트에 띄어주는 기능 추가

### ISSUE THREAD

**Issue by MinSeungHyun** [MinSeungHyun/yontil#3]

**Comment by sagittarius05** [comment]
'이번주차 할일'과 '전체 주차 할일' 때문에 이번주 과제는 두번씩 출력됨

기존에는 '주차 별 학습 활동' 박스 안에서만 검색 가능하게 만들었음

하지만 영강에서는 런어스상 한글 텍스트가 없어서 영어 버전도 예외 처리를 해줘야 함.
